### ISSUE TITLE
Couldn't create HTTP server.

### ISSUE THREAD

**Issue by mrwert** [guidoreina/gwebs-plusplus#1]
Hello!
Couldn't create HTTP server.
FreeBSD 10.3, gcc 4.8.5 and clang 3.4.1.
Starts without problems on Debian 8.4.0.
Thanks!

**Comment by guidoreina** [comment]
Can you post your configuration file here (gwebs++.conf)?

You can check the following in your configuration file:
- Does the "root" directory exist?
- Is it because it cannot bind to one of the interfaces? Please check the section "listen" in the configuration file, and compare it with the output of ifconfig.
- If you are using HTTPS, please check that the certificate and key files exist. If you are using the same ones I am using, try to comment out the section "ssl" and see if it starts. If it doesn't, then we know it is not because of that.

Thank you for your interest and best regards :)

**Comment by mrwert** [comment]
Hello!
[it works]
Debian 8.4.0 with default the gwebs++.conf (root = /home/guido -> root = /home/name).
I deleted a string -DHAVE_SSL because libcrypto.so: error adding symbols: DSO missing from command line (Debian).

[it doesn't work]
Couldn't create HTTP server (FreeBSD 10.3 and OpenBSD 5.8, BSD curse? :)).

I have tried with and without ssl.

http {
  directory_listing = yes
  log_requests = yes
  hosts {
    example.com {
    listen {
      127.0.0.1:8080 = http
    }
    root = /home/name
  }
}

Thanks!

**Comment by mrwert** [comment]
net/internet/http/server.cpp: 285
if (!listen(addr, https)) {
  return false;
}

**Comment by guidoreina** [comment]
Can you add the following line in net/internet/http/server.cpp:285 ?

if (!listen(addr, https)) {
  printf("Address: '%s', HTTPS: %s.\n", listener, https ? "yes" : "no"); // Add this line.
  return false;
}

I guess you will get "Address: '127.0.0.1:8080', HTTP: no".
Is there something listening already in port 8080? (just in case). With Linux you can do:
netstat -anp | grep LISTEN | grep 8080
(I don't have FreeBSD right now and cannot check)

I have FreeBSD 10.3 at home, I will test tonight your configuration and hopefully I get the same error, then it would be easier to fix :)

**Comment by mrwert** [comment]
If 127.0.0.1:8080 = http -> "Address: '127.0.0.1:8080', HTTP: no". Couldn't create HTTP server.
If 127.0.0.1:8080 = https -> "Address: '127.0.0.1:8080', HTTP: yes". Couldn't create HTTP server.
netstat -an -f inet | grep LISTEN -> 8080 not found :)

**Comment by guidoreina** [comment]
I will check then tonight from home, there might be something wrong.
Thank you very much :)

**Comment by mrwert** [comment]
Thanks! It's important for me because i study your projects. 
Good job and good code style.

**Comment by guidoreina** [comment]
I could reproduce the problem and fix the bug.
Thank you and I am happy to hear my project helps you :)

**Comment by mrwert** [comment]
eee...
...server has started (FreeBSD 10.3, 11.0; OpenBSD 5.8; 5.9).
Thank you very much!

**Comment by guidoreina** [comment]
Thanks to you for testing it and finding out it was not working :)
