### ISSUE TITLE
The special identifier "final".

### ISSUE THREAD

**Issue by mrwert** [guidoreina/gwebs-plusplus#3]
Hello!

Clang: error...

net/listener.h:
13: #if _LP64
14:   struct listener __final : protected socket, public io::event_handler {

Solution:
14:   struct listener final : protected socket, public io::event_handler {

Thanks :)

**Comment by guidoreina** [comment]
Hello Donald,

Thank you for reporting it with the solution. I have just committed. Sorry, I forgot to write in the comment that it was thanks to you.

**Comment by mrwert** [comment]
It's not necessarily.
The main thing for me is delete bugs and errors.

Thanks.
