### ISSUE TITLE
Others.

### ISSUE THREAD

**Issue by mrwert** [guidoreina/gwebs-plusplus#4]
Hello! :)

Warning: struct 'red_black_tree' was previously declared as a class:
util/red_black_tree.h:
649: return ..........const **struct** red_black_tree<T>&>(*this).minimum(x));

Warning: hides overloaded virtual function:
net/internet/http/server.h:
24: virtual bool create(const char\* config_file, const char\* mime_types_file);
net/tcp_server.h:28:
28: virtual bool create();

Warning: 'va_start' has undefined behavior with reference types:
util/configuration.cpp:
602: va_start(ap, **valuelen**);
621: va_start(ap, **count**);

Thanks.

**Comment by guidoreina** [comment]
Thank you again for reporting a problem :). It looks like clang++ finds more things than g++
