### ISSUE TITLE
Couldn't connect (FreeBSD 11.0).

### ISSUE THREAD

**Issue by mrwert** [guidoreina/gwebs-plusplus#5]
Hello!

```
net::socket s;
if (!s.connect(net::socket::STREAM, addr, TIMEOUT)) {
  fprintf(stderr, "Couldn't connect.\n");
  return;
}
```

net/socket.cpp:
51: `if ((::connect(_M_fd, reinterpret_cast<const struct sockaddr*>(&addr), sizeof(socket_address)) < 0) && (errno != EINPROGRESS)) {`

Solution:
51: `if ((::connect(_M_fd, reinterpret_cast<const struct sockaddr*>(&addr), addr.size()) < 0) && (errno != EINPROGRESS)) {`

Thanks!

**Comment by guidoreina** [comment]
Thank you for finding and reporting the bug :)
The latest socket class I have in github is in the downloader project. It seems I fixed it there but forgot it to fix it here.

**Comment by mrwert** [comment]
I use socket class in my projects. Will this class be ported to Windows?

**Comment by guidoreina** [comment]
Take then the socket class in the downloader project, it is the latest socket class I have in github.
I started writing a net library, but then stopped and worked on another projects :). I would like to finish it one day, and also port it to Windows, but who knows which project will come to my mind next :)

**Comment by mrwert** [comment]
:)
I will be very pleased if the socket class from the downloader project will work in Windows. Otherwise i will have to do it myself If this does not happen.

**Comment by guidoreina** [comment]
It wouldn't be difficult to port the socket class to Windows. What is difficult is to port the downloader or the webserver project to Windows if you want to be able to handle many connections simultaneously. Linux uses epoll() and Windows uses IOCP (I/O completion ports):
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365198(v=vs.85).aspx

With epoll() you get notified when a socket is readable/writable and then you can call recv()/send(). With IOCP you get notified with the result of the operation (once the operation has finished).

Boost asio uses the IOCP model. While it is possible to simulate IOCP under Linux using epoll(), I think it is not possible to simulate epoll() under Windows (you have the select() function, but it is slow when you have many file descriptors).

I have a socket class which works under Linux and Windows in one of my unfinished projects.

**Comment by mrwert** [comment]
Thank You!
